### ISSUE TITLE
Description Mirroring failed during the operation

### ISSUE THREAD

**Issue by liujie12** [h-mdm/remote-control#46] opened 2022-10-20 05:34 UTC
If you do not click the interface for more than a few seconds after the remote interface is successfully mirrored, the web interface becomes stuck and does not change with the android interface，However, the click blocking effect will still pass to the android side, but the web side will not move
![image](https://user-images.githubusercontent.com/49354279/196864366-de9dbe11-4bc6-463c-85e7-de373d89381d.png)

**Comment by h-mdm** [comment] 2022-10-20 08:33
This issue is apparently a duplicate of https://github.com/h-mdm/remote-control/issues/45

**Closed by h-mdm** 2022-10-20 08:33 UTC
